#!/bin/bash
BASEDIR=$(dirname $0)

case "$1" in
  install)
      case "$2" in
      vim-config)
        cd $BASH_MANAGER_PATH/packages
        git clone https://github.com/mtzd/vim-config
        chmod 755 $BASH_MANGER_PATH/packages/vim-config/install.sh
        cd $BASH_MANGER_PATH/vim-config/
        sh install.sh
        exit 0
        ;;
      *)
        echo "Available packages:\n vim-config"
        exit 1
      esac
    ;;
  *)
    echo $"Usage: $0 {install}"
    exit 1
esac
